# Generated by Django 2.2.5 on 2020-11-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201118_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cardExpMonth',
            field=models.CharField(default='**', max_length=2),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cardExpYear',
            field=models.CharField(default='****', max_length=4),
        ),
    ]
