# Generated by Django 2.2.5 on 2020-11-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('reservations', '0003_auto_20201118_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('roomtype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.RoomType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
