# Generated by Django 2.2.5 on 2020-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_bookedday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedday',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
