# Generated by Django 2.2.5 on 2020-11-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_bookedday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bedtype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='rooms.BedType'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roomtype',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='rooms.RoomType'),
        ),
    ]
