# Generated by Django 2.2.5 on 2020-11-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20201120_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedday',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookedday',
            name='roomtype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rooms.RoomType'),
        ),
    ]
