# Generated by Django 2.2.5 on 2020-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('reservations', '0010_auto_20201121_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedday',
            unique_together={('roomtype', 'day')},
        ),
    ]
